title: Eleonora & Tammo
author: Tammo Ippen
name: Tammo Ippen
email: tammo.ippen@posteo.de

lang: de
description: >
  Eine sehr schöne Beschreibung!
excerpt_separator: <!--more-->

markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock

url: "http://eleonora.tammo.io"

sass:
  style: compressed

kramdown:
  input: GFM
